// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tafdzufjubadcxsvhkze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhZmR6dWZqdWJhZGN4c3Zoa3plIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNTgzMjQsImV4cCI6MjA2NjgzNDMyNH0.3MwCdZSkC0JB0cmk9KB6VnAm3xX356kgNrakguJA_JI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});